spring:
  application:
    name: miniwallet
  docker:
    compose:
      enabled: false

  # --- Database Connection ---
  datasource:
    url: jdbc:postgresql://localhost:5432/miniwallet
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  # --- Hibernate & JPA Settings ---
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

# --- Logging Configuration ---
logging:
  file:
    name: log/wallet-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    com.assessment.miniwallet: INFO